name: post-office
version: '0.6'
main: org.peakimo.postoffice.Post_office
api-version: '1.16'
commands:
  post-request:
    description: request postman!
    usage: /<command>
  sendmail:
    description: Send Mail!
    usage: /<command>

